version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
      - DB_URL=file:/app/data/local.db
    volumes:
      - sqlite_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3010"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data: